### ISSUE TITLE
netCDF sync

### ISSUE THREAD

**Issue by fjansson** [dalesteam/dales#44]
With the switch to netCDF v4 in DALES 4.2 one drawback appears: the netCDF output files are not readable while the simulation is running, and may not be readable if the run crashed or was interrupted. Reported by Kevin Helfer.

## Suggestion
add NF90_SYNC(ncid) calls:
* when writing a restart file
* at configurable intervals during the simulation

## Workarounds
switch back to netCDF v3 by replacing the netCDF creation call
```
- iret = nf90_create(fname,NF90_NETCDF4,ncid)
+ iret = nf90_create(fname,NF90_SHARE,ncid)
```

Or add sync calls as in 2e5b07a4523 where the interval is not yet configurable, overhead of this still unknown.

**Comment by Chiil** [comment]
The problem is only a file lock, as long as you sync, the files will be readable after termination, even after a crash. If you copy the file to another while running, you can still view the output while the model continues.

**Comment by fjansson** [comment]
I just tried looking at the netcdf files with ncdump while DALES is running (no sync calls). The files are readable, but show no data, only the variable definitions. Copying the file didn't change this. I've tried ncview as well, it says no displayable variables found. If I look at fielddumps which tend to be larger, I see the file size growing but ncdump still doesn't show any data, during the run or after if I interrupt with control-C.

This used to be different with netCDF v3, I think either netCDF v4 or enabling compression made sync calls necessary to get intermediate results.

Maybe I misunderstood the message, but anyway, if I add sync calls, I have been able to view the netCDF output while DALES is running, also without copying the files.

**Comment by Chiil** [comment]
I think you understood it right :). With MicroHH, I cannot view the files while running even if I sync.

**Comment by fjansson** [comment]
Now I understand. On some systems (ECMWF I think), I've used `export HDF5_USE_FILE_LOCKING=FALSE`, which did help with some netCDF syncing issues. I still had to add the sync calls in the code though.

**Comment by jiskattema** [comment]
Did you try to add the NF90_SHARE flag when opening the netcdf file? That is required for the sync() function to work. From the [fortran 90 website](https://www.unidata.ucar.edu/software/netcdf/docs-fortran/f90-use-of-the-netcdf-library.html):

```
Finally, you should explicitly close all netCDF datasets that have been opened for writing by calling
NF90_CLOSE. By default, access to the file system is buffered by the netCDF library. If a program
terminates abnormally with netCDF datasets open for writing, your most recent modifications may be
lost. This default buffering of data is disabled by setting the NF90_SHARE flag when opening the
dataset. But even if this flag is set, changes to attribute values or changes made in define mode are not
written out until NF90_SYNC or NF90_CLOSE is called.
```

**Comment by fjansson** [comment]
Adding sync calls without the NF90_SHARE flag did make the file readable while DALES is running (I've got the impression that explicit sync calls are fine even when not using the share flag).

Creating the file with mode `IOR(NF90_NETCDF4, NF90_SHARE)` and not calling sync is not enough, the result is the same as without the SHARE flag.

**Comment by fjansson** [comment]
In branch to4.3, the flag `lsync` was added to NAMNETCDFSTATS. If set to true, NF90_SYNC(ncid) is called after writing to the netcdf files. If the sync calls turn out to add a lot of overhead, we may consider syncing only every n:th time step.

On Cartesius I have occasionally seen that the netcdf files are still not readable while DALES is running, but then copying the files somewhere else has worked. It seems we cannot do more in DALES - closing this issue.
