### ISSUE TITLE
ASCII output files are overwritten on warm starts

### ISSUE THREAD

**Issue by fjansson** [dalesteam/dales#47]
ASCII output files are overwritten on warm starts. It would be better to open them for appending. Currently seeing this for the RCEMIP branch of DALES, not yet sure its a general problem.

Affected files: tmser1, tmsurf, svNNNflx, flux1, flux2, budget
RCEMIP specific files: tmrce, rcemip

**Comment by jchylik** [comment]
Although appending the files seems convenient, there will be couple of issues with it:

1. Interlaying parts of timeseries -- the early outputs from warm start will have earlier time than the last few outputs from the original run.

2. What if there was a change in some of namelists for statistics? That would lead to situation where the newly outputted lines consist of a different number of columns than the earlier lines. 

Perhaps a better would be to first make a backup copy of the original output files and then start overwriting them, wouldn't it?

**Comment by fjansson** [comment]
Good points!

1. That's right, if the earlier run continues past the last restart point, and writes more output. This is annoying. The NetCDF output deals with this by finding the proper index to start writing from,
so that it overwrites the duplicate time steps from the last run. I don't want to try this with ascii files.

2. My feeling at the moment is that if one changes the namoptions mid-run, one can move away the old files before restarting. 

I think I would prefer appending to the files at restart even with these issues, over losing the data in them at restart. If we start moving existing files before overwriting, we have to invent a numbering scheme because there may be many old files. Besides, the current behaviour surprised me.

I'm currently planning a 100-day run. It has to be done in 10 to 20 pieces because of the clusters wall-clock time limits. I will do the runs so that they end with writing a restart file.


**How it works currently**

modtimestat.f90, inittimestat() opens many of these files with
```
open (ifoutput,file='tmser1.'//cexpnr,status='replace',position='append')
```
the writes the file header, and closes the file again. `status='replace'` here causes the file to be deleted if it exists. For each line appended to the file later in `timestat`, the file is opened, written to and closed.

**My suggestion** 

in inittimestat(), open with status='replace' and write the header only if lwarmstart is .false.
On a cold start, files from a previous run are removed. On a warm start, existing files will be
appended to. This indeed suffers from the issues mentioned above. 

We could add a configuration file for selecting append/overwrite. On the other hand, if one wants overwrite, one can also remove/move/rename the old files before starting a new run. I think append would be a nicer default behaviour.

**Comment by fjansson** [comment]
Changed in branch to4.3. ASCII files are no longer automatically overwritten. For the old behavior, remove the ascii output files before starting a new run.
