### ISSUE TITLE
modlsmcrosssection missing if/endif

### ISSUE THREAD

**Issue by jchylik** [dalesteam/dales#58]
The file modlsmcrosssection.f90 deals with statistics of a heterogeneous surface.
Although the heterogenous surface patches can be used both for isurf=1 and 2 (and possibly more), the subroutines in modlsmcrosssection.f90 require variables that are initialised _only in case isurf=1_.
In other cases, the DALES run will **crash** without any warning. 

Proposed correction:
line 74:
`use modsurfdata, only : isurf `

line 94:
```
if (lcross .and. (isurf .ne. 1)) then
  lcross = .FALSE.
  write (6,*) "Ignoring lcross, lsmcrossection currently implemented only for isurf==1."
endif

```

**Comment by fjansson** [comment]
Which variables are not initialized in the other cases? (tsoil and phiw I would guess without digging). 

@julietbravo do we need this statistics output for other isurf settings? The variables from the surfcross file could be useful in the other cases perhaps. 

For now, I will add this check to avoid crashing.

**Comment by jchylik** [comment]
Crosssestion of surface properties in case isurf==2 would be nice, but only variables that is currently allocated and easy to access is _tskin_ (ie. surface skin temperature).
