### ISSUE TITLE
Minor issue in defining startfile in Namoptions

### ISSUE THREAD

**Issue by rbschulte** [dalesteam/dales#74]
Bart van Stratum and I found that the model gave an error when running from a warm start since the transition from Cartesius to Snellius.

On Cartesius, I could define the startfile for the warm start without quotation marks in Namoptions, e.g. startfile =  initd004h30mxxxxxxxx.602.
On Snellius, this results in an error when DALES reads the namoptions: STOP ERROR: Problem in namoptions RUN

The solution is to add quotation marks (' ') to the name of the startfile in Namoptions, e.g. startfile =  'initd004h30mxxxxxxxx.602'.
I have not checked the results, but the model is running at the moment with these changes. 

This is probably not a problem with the model itself, but the use of quotations is not mentioned in the documentation of DALES (namoptions.pdf or dales-manual.pdf). The quotations are found in some of the example cases. I hope this information is helpful.
Note that I am currently using an altered version of DALES v4.2.

**Comment by jchylik** [comment]
> The solution is to add quotation marks (' ') to the name of the startfile in Namoptions

Isn't that a basic convention that string values should be always surrounded by single quotation marks (or double ones)?

That said, you are right that the quotation marks are missing in the table in namoptions overview.

**Comment by fjansson** [comment]
Thank you Ruben for the report. Maybe newer compilers enforce quotation marks while the older don't. The namelist reading is built into fortran, we don't have much control over it. So let's update the documentation and the example cases to use quotation marks.

**Comment by fjansson** [comment]
Documentation fixed in version 4.4.
