### ISSUE TITLE
Promble about the radiation

### ISSUE THREAD

**Issue by rico12312** [dalesteam/dales#89]
When I used the radiation part of the model, I found I lacked the input file and found them in Git Hub. However, I can't understand them, especially the ckd. inp and the cldwtr.inp.

**Comment by jchylik** [comment]
> I lacked the input file and found them in Git Hub

Hello, these files mostly describe the radiative properties of the part of the atmosphere above the computational domain.
In the upper few layers, a blending is usually applied. 

> However, I can't understand them, especially the ckd. inp

This one kind of describes the concentration of ozone and other gasses in the upper troposphere and above. If you are working with simulation in subtropics, you can in the first approximation leave it as it is.
 
> and the cldwtr.inp.

This one is bit more complicated, describe something related to optical properties of droplets. However usually it is bypasses in a radiation code by hard-coded values.

**Comment by rico12312** [comment]
Thank you very much, but please tell me to adjust the ckd. inp because there are almost no comments in the file.

**Comment by rico12312** [comment]
Thank you very much, but please tell me how to adjust the ckd. inp because there are almost no comments in the file.

**Comment by rico12312** [comment]
Especially like H2O   3; 1 12 11 3， what is line 3 and the line 1 12 11 3， and the value why not complete if it is a matric/table， because the value is null？

**Comment by jchylik** [comment]
> there are almost no comments in the file

Sadly, none. I think there were no comments because of machine readability.

> H2O 3; 1 12 11 3， what is line 3 and the line 1 12 11 3

The file is read for example in init_ckd in modradfull.f90
https://github.com/dalesteam/dales/blob/main/src/modradfull.f90#L1732-L1766

The first part define bands, the later part gas effect on these radiative bands.

**Comment by rico12312** [comment]
Thank you very much; I will learn more about the code.
