### ISSUE TITLE
The unit of variables of the file scale.inp

### ISSUE THREAD

**Issue by rico12312** [dalesteam/dales#91]
Hello, thank you for creating the great model. Recently I have been confused about the unit in the file scale.inp. The unit of z is m, but I don't know the unit of the following column.

**Comment by jchylik** [comment]
>  I have been confused about the unit in the file scale.inp. The unit of z is m, but I don't know the unit of the following column.

Hello, all the columns in the input are well explained on pages 11--14 of the manual:
[dales-manual.pdf](https://github.com/dalesteam/dales/blob/main/utils/doc/input/dales-manual.pdf)

**Comment by rico12312** [comment]
Thank you, but I have looked into it for the file and I am still confused，so I seek help here.
<img width="576" alt="屏幕截图 2024-01-24 204840" src="https://github.com/dalesteam/dales/assets/144920926/7f108865-02c1-4874-b341-f965b8278f6c">

**Comment by rico12312** [comment]
Because if it is the number density，it is too low in the case input file

**Comment by jchylik** [comment]
> if it is the number density，it is too low in the case input file
 
Is it, though? Most of the simulations start without rain, or with very little of it. You would expect the more rainfall to develop after the spinup.

**Comment by rico12312** [comment]
Sorry, I wasn't clear. I meant if the parameters are the number concentration of gases, not rainwater。 For example, in cases/GOAMAZON14/ControlExperiment/input/scalar.inp.047, if the unit is the number concentration (molecules/m3) for N2， it is too low.

**Comment by jchylik** [comment]
> I meant if the parameters are the number concentration of gases, not rainwater。 For example, in cases/GOAMAZON14/ControlExperiment/input/scalar.inp.047

Looking at the case, it depends on what the units are.
mols ? ppm ? ppb?

```
 ... O2           N2         HNO3        H2O2       CO2
 ... 0.200E+09   0.800E+09   0.000E+00   0.000E+00  0.438E+06
```
[cases/GOAMAZON14/ControlExperiment/input/scalar.inp.047#L3)](https://github.com/dalesteam/dales/blob/main/cases/GOAMAZON14/ControlExperiment/input/scalar.inp.047#L3)

Wait, 0.800E+09 for nitrogen? It looks like the units are ppb (particles-per-billion)

**Comment by rico12312** [comment]
Thank you
